### PR TITLE
The same as #77

### PR DESCRIPTION
**Pull request by BlueCocoa**
The same as #77
Headers at /llama_cpp/Sources/llama/Headers in Project Navigator

Signed-off-by: 0xBBC 0xbbc@0xbbc.com

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/132" target="_blank">ReviewNinja

**Comment by BlueCocoa** [comment]
LBTM

**Comment by BlueCocoa** [comment]
LGTM

**Comment by 0xsuu** [comment]
Only for library? Should we do on all of them?

**Comment by 0xsuu** [comment]
LOL Only when we need, LGTM

**Pull request merged**
