### PR TITLE
Add softmax to generate normalised probabilities

### PR DESCRIPTION
**Pull request by 0xsuu**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/155" target="_blank">ReviewNinja

**Comment by 0xsuu** [comment]
LGTM @BlueCocoa

**Comment by 0xsuu** [comment]
LGTM

**Comment by 0xsuu** [comment]
LGTM @BlueCocoa

**Comment by BlueCocoa** [comment]
LGTM

**Pull request merged**
