### PR TITLE
Add google lint

### PR DESCRIPTION
**Pull request by 0xsuu**
One question,

Any style error, stop the build, or just warning developer?
Style error: e.g. using tab instead of space, few naming issue, etc.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/62" target="_blank">ReviewNinja

**Comment by 0xsuu** [comment]
@Giolno This pr changed all tabs to 4 spaces, pls review the code by viewing "File changed"

**Comment by 0xsuu** [comment]
@Sunbelife Can you:
- Find rest style errors(run `./lint/lint_cpp.py`) and fix them?
- After this branch merged, merge master into your branch, fix conflicts and style errors.

**Comment by Sunbelife** [comment]
I think if there comes to a style error,Stop building.

**Comment by 0xsuu** [comment]
@Sunbelife space around ",", and  lowercase stop, remove to as well.

**Comment by BlueCocoa** [comment]
Just warning...

**Comment by 0xsuu** [comment]
@Giolno need your opinion

**Comment by ghost** [comment]
A warning after succeed build is OK, I think.

**Pull request merged**
