### PR TITLE
Add Random Bool Generator

### PR DESCRIPTION
**Pull request by ghost**
Added random bool generator and optimise some functions.

Signed-off-by: Zongyu zy728@york.ac.uk

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/131" target="_blank">ReviewNinja

**Comment by ghost** [comment]
@al1enSuu

**Comment by 0xsuu** [comment]
Coverage -1.7% which is not a good sign, so add test for the newly added functions to cover them. Check [UtilityDataGeneratorUnitTest.cpp](https://github.com/Llama-Group/Project-Llama/blob/master/llama_cpp/test/Llama_UnitTest/UtilityDataGeneratorUnitTest.cpp), append your tests behind it. And do the NullPointer test in a new pr after solve the coverage on this pr.

**Comment by 0xsuu** [comment]
LGTM

**Comment by BlueCocoa** [comment]
LGTM

**Pull request merged**
