### PR TITLE
Initial commit for LLObjcect

### PR DESCRIPTION
**Pull request by BlueCocoa**
Initial version of LLObject with a few examples.

Signed-off-by: 0xBBC 0xbbc@0xbbc.com

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/122" target="_blank">ReviewNinja

**Comment by BlueCocoa** [comment]
LGTM

**Comment by 0xsuu** [comment]
LGTM. PL

**Comment by 0xsuu** [comment]
Move to new Folder "DataStructure" @BlueCocoa

**Pull request merged**
