### PR TITLE
Changed - to +

### PR DESCRIPTION
**Pull request by 0xsuu**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/148" target="_blank">ReviewNinja

**Comment by 0xsuu** [comment]
LTGM

**Comment by 0xsuu** [comment]
LBTM @BlueCocoa beg for a star

**Comment by BlueCocoa** [comment]
LGTM

**Comment by 0xsuu** [comment]
LGTM

**Pull request merged**
