### PR TITLE
Add google test

### PR DESCRIPTION
**Pull request by 0xsuu**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/67" target="_blank">ReviewNinja

**Comment by 0xsuu** [comment]
@Giolno @BlueCocoa Pls review.

**Comment by BlueCocoa** [comment]
LGTM

**Comment by 0xsuu** [comment]
LGTM

**Comment by 0xsuu** [comment]
Branch kept for @Giolno

**Pull request merged**
