### PR TITLE
Modify Xcode generation

### PR DESCRIPTION
**Pull request by 0xsuu**
Now works perfectly, but need refinement on the move of library.
- [x] Still not showing .h files
- [ ] Movement of libllama.a is not perfect

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/82" target="_blank">ReviewNinja

**Comment by 0xsuu** [comment]
Let this pass if it is good to you. @BlueCocoa

**Comment by BlueCocoa** [comment]
As for the first question, it was already fixed, but just need another ninja star to be able to merge. Please see #77

**Comment by 0xsuu** [comment]
LGTM

**Pull request merged**
