### PR TITLE
Add unit test for Utility/Functor.h

### PR DESCRIPTION
**Pull request by BlueCocoa**
Add unit test for Utility/Functor.h

Signed-off-by: 0xBBC 0xbbc@0xbbc.com

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/120" target="_blank">ReviewNinja

**Comment by BlueCocoa** [comment]
LGTM

**Comment by BlueCocoa** [comment]
LGTM

**Comment by 0xsuu** [comment]
LGTM

**Pull request merged**
