### PR TITLE
Add benchmark item

### PR DESCRIPTION
**Pull request by Sunbelife**
I added the bubblesort and selectionsort to benchmark.

Signed-off-by: Sunbelife Sunbelife@foxmail.com

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Llama-Group/Project-Llama/pull/118" target="_blank">ReviewNinja

**Comment by 0xsuu** [comment]
LGTM

**Comment by Sunbelife** [comment]
@BlueCocoa Please review my code. :。

**Comment by BlueCocoa** [comment]
LGTM

**Pull request merged**
